name: Swift Testing
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/swift-test.yaml"
      - "**.swift"
      - "Package.resolved"
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: "amazon/dynamodb-local:latest"
        ports:
          - "8001:8000"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          key: swift-build-${{ runner.os }}-${{ runner.arch }}
          path: .build

      - run: swift build
      - run: swift test
        env:
          SMALL: true
          MEDIUM: true
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
